//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftBots.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinecraftBots.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [Control]
        ///name=%RANDOM%
        ///;%RANDOM%表示随机长度5-14字符
        ///;可以用xxx_%RANDOM%这样加上前缀
        ///
        ///maxbots=50
        ///;最大假人数目
        ///
        ///protocol=0
        ///;协议号，0即自动获取motd中协议
        ///
        ///cooldown=10
        ///;假人进入间隔
        ///;注:队列算法中直到有假人成功登入才休眠线程
        ///
        ///tclear=5000
        ///;清理周期
        ///
        ///[Bot]
        ///motdSend=false
        ///;是否发送ping包
        ///;由于需要多建立一个连接，多少都会影响效率
        ///
        ///ClientSettingSend=true
        ///;是否发送客户设置
        ///
        ///tabComplete=0
        ///;发送TAB补全封包，单位频率:毫秒(0为禁用
        ///;(超耗代理资源
        ///
        ///reJoin=20000
        ///;重新加入间隔，单位:毫秒
        ///
        ///[Info]
        ///chats=chatlist.txt
        ///;聊天信息文件
        ///
        ///Wlogs=true
        ///;记录???
        ///
        ///[Proxy]
        ///url=http://www.89ip.cn/tqdl.html?api=1&amp;num=2000
        ///;代理地址
        ///
        ///co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultConfig {
            get {
                return ResourceManager.GetString("DefaultConfig", resourceCulture);
            }
        }
    }
}
